name: Docs

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      -  main

jobs:
  rustdoc:
    name: Rustdoc
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'swc-project/swc'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Create rustdoc
        run: cargo doc --all --features plugin_transform --features ecma_loader --features ecma_utils --features ecma_quote --features ecma_visit --features ecma_transforms --features __testing_transform

      - name: Create CNAME
        run: |
          echo 'rustdoc.swc.rs' > target/doc/CNAME

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: target/doc
          clean: true
          git-config-email: bot@swc.rs
          repository-name: swc-project/rustdoc
          commit-message: "Update"
          single-commit: true